# Generated by Django 4.2.25 on 2025-10-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('memberships', '0006_workoutsession_weeklygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='payments.payment'),
        ),
    ]
