#!/bin/bash
# Fix migration dependencies

echo "=========================================="
echo "Fixing Migration Dependencies"
echo "=========================================="
echo ""

cd /home/magmafit/magma7_proj
source ~/virtualenv/magma7_proj/3.12/bin/activate
export DJANGO_SETTINGS_MODULE=magma7.settings.production

# Fix 0010 migration dependencies
echo "1. Fixing 0010 migration dependencies..."
cat > cms/migrations/0010_alter_mediaasset_options_and_more.py << 'PYEOF'
# Generated by Django 5.1.4 on 2025-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_errorlog'),  # Changed from 0009_merge
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Assets'},
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='usage',
            field=models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero Image'), ('slide', 'Slide Background'), ('gallery', 'Gallery Image'), ('profile', 'Profile Photo'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('general', 'General Use')], default='general', help_text='How this asset is being used', max_length=20),
        ),
    ]
PYEOF

echo "✓ Fixed 0010 migration"

# Show migrations
echo ""
echo "2. Checking migrations..."
python manage.py showmigrations cms

# Run migrations
echo ""
echo "3. Running migrations..."
python manage.py migrate cms

# Verify table exists
echo ""
echo "4. Verifying ErrorLog table..."
python manage.py shell << 'PYEOF'
from cms.models import ErrorLog
try:
    count = ErrorLog.objects.count()
    print(f"\n✓ SUCCESS! ErrorLog table exists with {count} entries.\n")
except Exception as e:
    print(f"\n✗ Error: {e}\n")
PYEOF

# Restart app
echo ""
echo "5. Restarting application..."
touch passenger_wsgi.py

echo ""
echo "=========================================="
echo "✓ Migrations fixed and applied!"
echo "=========================================="
echo ""
