# Generated by Django 4.2.25 on 2025-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_guide_description',
            field=models.TextField(blank=True, help_text='Description of what the free guide contains'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_guide_text',
            field=models.CharField(default='Get Now', help_text='Text shown on the free guide button', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_guide_title',
            field=models.CharField(blank=True, default='Free Fitness Guide', help_text='Title of the free guide for admin reference', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_guide_url',
            field=models.URLField(blank=True, help_text='URL to download or access the free guide (PDF, form, etc.)'),
        ),
    ]
