# Generated by Django 4.2.25 on 2025-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesettings_free_guide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(default='Join thousands of satisfied members who have transformed their lives at Magma7Fitness', help_text='Description text for CTA section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_headline',
            field=models.CharField(default='Ready to Start?', help_text='Main headline for CTA section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_image_url',
            field=models.URLField(blank=True, help_text='Background or feature image for CTA section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_text',
            field=models.CharField(default='Sign Up Today', help_text='Text for primary CTA button', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_primary_url',
            field=models.CharField(default='/accounts/signup/', help_text='URL for primary CTA button', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_text',
            field=models.CharField(default='Learn More', help_text='Text for secondary CTA button', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_secondary_url',
            field=models.CharField(default='/about/', help_text='URL for secondary CTA button', max_length=200),
        ),
    ]
