# Generated by Django 4.2.25 on 2025-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutgalleryimage_aboutpage_aboutstatistic_corevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our World-Class Facilities', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('intro_title', models.CharField(default='Everything You Need', max_length=200)),
                ('intro_content', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Ready to Experience It?', max_length=200)),
                ('cta_description', models.TextField(default='Visit us for a free tour')),
                ('cta_button_text', models.CharField(default='Book a Tour', max_length=50)),
                ('cta_button_url', models.CharField(default='/contact/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facilities Page Content',
                'verbose_name_plural': 'Facilities Page Content',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fitness_center', help_text='Material icon name', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Facility image')),
                ('features', models.TextField(blank=True, help_text='Comma-separated features list')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('role_category', models.CharField(choices=[('trainer', 'Fitness Trainer'), ('nutritionist', 'Nutritionist'), ('manager', 'Manager'), ('instructor', 'Instructor'), ('support', 'Support Staff'), ('specialist', 'Specialist')], default='trainer', max_length=20)),
                ('bio', models.TextField(help_text='Brief biography')),
                ('image_url', models.URLField(help_text='Profile photo')),
                ('specialties', models.TextField(blank=True, help_text='Comma-separated specialties')),
                ('certifications', models.TextField(blank=True, help_text='Certifications and qualifications')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Meet Our Team', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('intro_title', models.CharField(default='Expert Guidance', max_length=200)),
                ('intro_content', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Join Our Team', max_length=200)),
                ('cta_description', models.TextField(default="We're always looking for talented individuals")),
                ('cta_button_text', models.CharField(default='View Careers', max_length=50)),
                ('cta_button_url', models.CharField(default='/careers/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Page Content',
                'verbose_name_plural': 'Team Page Content',
            },
        ),
    ]
