# Generated by Django 5.1.4 on 2025-10-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_logo_favicon_to_sitesettings'),
        ('cms', '0006_heroslide'),
    ]

    operations = [
    ]
