# Generated by Django 5.1.4 on 2025-10-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_media_center_and_file_uploads'),
        ('cms', '0007_merge_20251020_1106'),
    ]

    operations = [
    ]
