# Generated by Django 5.1.4 on 2025-10-20 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this asset', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('file', models.FileField(help_text='Upload file (images, videos, documents)', upload_to='media_assets/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'mp4', 'webm', 'pdf', 'ico'])])),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20)),
                ('usage', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero Image'), ('slide', 'Slide Background'), ('gallery', 'Gallery Image'), ('profile', 'Profile Photo'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('general', 'General Use')], default='general', help_text='Primary usage of this asset', max_length=20)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for images (SEO)', max_length=200)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Center',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_timesta_55fd6c_idx',
            old_name='cms_errorlo_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_severit_f630f6_idx',
            old_name='cms_errorlo_severit_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_resolve_fb7ea4_idx',
            old_name='cms_errorlo_resolve_idx',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image (recommended: 1920x1080px or larger)', null=True, upload_to='hero_slides/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload favicon (.ico or .png, 32x32 or 64x64 pixels)', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='OR provide favicon URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo (PNG/SVG with transparent background)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OR provide logo URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR provide image URL (if not uploading)'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
