# Generated by Django 5.1.4 on 2025-10-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_errorlog'),
        ('cms', '0008_merge_20251020_1136'),
    ]

    operations = [
    ]
