# Generated by Django 5.1.4 on 2025-10-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_mediaasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title/caption', max_length=150)),
                ('image_url', models.URLField(help_text='Image URL (from Media Center or external)')),
                ('description', models.TextField(blank=True, help_text='Optional description shown on hover')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in the gallery')),
            ],
            options={
                'verbose_name': 'Home Gallery Image',
                'verbose_name_plural': 'Home Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Center'},
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='usage',
            field=models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero Image'), ('slide', 'Slide Background'), ('gallery', 'Gallery Image'), ('profile', 'Profile Photo'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('general', 'General Use')], default='general', help_text='Primary usage of this asset', max_length=20),
        ),
    ]
