# Generated by Django 5.1.4 on 2025-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_errorlog'),  # Changed from 0009_merge
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Assets'},
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='usage',
            field=models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero Image'), ('slide', 'Slide Background'), ('gallery', 'Gallery Image'), ('profile', 'Profile Photo'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('general', 'General Use')], default='general', help_text='How this asset is being used', max_length=20),
        ),
    ]
