# Generated by Django 5.1.4 on 2025-10-20 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_0004_errorlog_0008_merge_20251020_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Center'},
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_timesta_55fd6c_idx',
            old_name='cms_errorlo_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_severit_f630f6_idx',
            old_name='cms_errorlo_severit_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='cms_errorlo_resolve_fb7ea4_idx',
            old_name='cms_errorlo_resolve_idx',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image (recommended: 1920x1080px or larger)', null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR provide image URL (if not uploading)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for images (SEO)', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(help_text='Upload file (images, videos, documents)', upload_to='media_assets/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'mp4', 'webm', 'pdf', 'ico'])]),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(help_text='Descriptive title for this asset', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='usage',
            field=models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon'), ('hero', 'Hero Image'), ('slide', 'Slide Background'), ('gallery', 'Gallery Image'), ('profile', 'Profile Photo'), ('thumbnail', 'Thumbnail'), ('icon', 'Icon'), ('general', 'General Use')], default='general', help_text='Primary usage of this asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload favicon (.ico or .png, 32x32 or 64x64 pixels)', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='OR provide favicon URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo (PNG/SVG with transparent background)', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OR provide logo URL'),
        ),
    ]
