# Generated by Django 5.1.4 on 2025-10-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Add field to HomeGalleryImage; depend on its creation migration
        ('cms', '0009_homegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegalleryimage',
            name='use_as_hero',
            field=models.BooleanField(default=False, help_text='Use this image as the Facilities page hero background'),
        ),
    ]
