# Generated by Django 5.1.4 on 2025-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_homegalleryimage_use_as_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_icon',
            field=models.CharField(default='groups', help_text='Material icon name for first stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_label',
            field=models.CharField(default='Members', help_text='Label for first stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat1_number',
            field=models.CharField(default='970+', help_text='Number to display (e.g., 970+, 1K+)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_icon',
            field=models.CharField(default='sports_gymnastics', help_text='Material icon name for second stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_label',
            field=models.CharField(default='Programs', help_text='Label for second stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat2_number',
            field=models.CharField(default='135+', help_text='Number to display (e.g., 135+, 200+)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat3_icon',
            field=models.CharField(default='workspace_premium', help_text='Material icon name for third stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat3_label',
            field=models.CharField(default='Trainers', help_text='Label for third stat', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat3_number',
            field=models.CharField(default='105+', help_text='Number to display (e.g., 105+, 50+)', max_length=20),
        ),
    ]
