# Generated by Django 4.2.25 on 2025-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesettings_cta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title/caption', max_length=150)),
                ('image_url', models.URLField(help_text='Image URL')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Gallery Image',
                'verbose_name_plural': 'About Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Magma7Fitness', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Brief introduction text')),
                ('hero_image_url', models.URLField(blank=True, help_text='Main hero image')),
                ('story_title', models.CharField(default='Our Story', max_length=200)),
                ('story_content', models.TextField(help_text="Tell your gym's story")),
                ('story_image_url', models.URLField(blank=True, help_text='Image for story section')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField()),
                ('mission_icon', models.CharField(default='track_changes', help_text='Material icon name', max_length=50)),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField()),
                ('vision_icon', models.CharField(default='visibility', help_text='Material icon name', max_length=50)),
                ('why_choose_title', models.CharField(default='Why Choose Us', max_length=200)),
                ('why_choose_description', models.TextField(blank=True)),
                ('gallery_title', models.CharField(default='Our Facility', max_length=200)),
                ('gallery_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Ready to Transform?', max_length=200)),
                ('cta_description', models.TextField(default='Join our community today')),
                ('cta_button_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_button_url', models.CharField(default='/memberships/plans/', max_length=200)),
                ('cta_image_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='AboutStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., "Active Members"', max_length=100)),
                ('value', models.CharField(help_text='e.g., "5000+"', max_length=50)),
                ('icon', models.CharField(default='trending_up', help_text='Material icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Statistic',
                'verbose_name_plural': 'About Statistics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='star', help_text='Material icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='check_circle', help_text='Material icon name', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Optional image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
