# Generated by Django 4.2.25 on 2025-10-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_facilitiespage_facility_teammember_teampage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title for admin reference', max_length=200)),
                ('image_url', models.URLField(help_text='Background image URL (use high-quality images, min 1920x1080)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in rotation')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
