# Generated by Django 4.2.25 on 2025-10-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_planfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image_url',
            field=models.URLField(blank=True, help_text='Featured image URL for the plan card'),
        ),
    ]
